package com.CSC;

import com.CSC._0.Rayyan.othman.api_demo.model.ApiCharacter;
import com.CSC._0.Rayyan.othman.api_demo.repository.ApiCharacterRepository;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

@Service
public class ApiCharacterService implements ApiCharacterService {

    private final ApiCharacterRepository repo;

    public ApiCharacterService(ApiCharacterRepository repo) {
        this.repo = repo;
    }

    @Override
    public List<ApiCharacter> getAllCharacters() {
        return repo.findAll();
    }

    @Override
    public Optional<ApiCharacter> getCharacterById(Long id) {
        return repo.findById(id);
    }

    @Override
    public ApiCharacter addCharacter(ApiCharacter c) {
        c.setCharacterId(null); // ensure autogenerated
        return repo.save(c);
    }

    @Override
    public Optional<ApiCharacter> updateCharacter(Long id, ApiCharacter incoming) {
        return repo.findById(id).map(existing -> {
            existing.setName(incoming.getName());
            existing.setDescription(incoming.getDescription());
            existing.setUniverse(incoming.getUniverse());
            existing.setSpecies(incoming.getSpecies());
            return repo.save(existing);
        });
    }

    @Override
    public boolean deleteCharacter(Long id) {
        if (!repo.existsById(id)) return false;
        repo.deleteById(id);
        return true;
    }

    @Override
    public List<ApiCharacter> getByUniverse(String universe) {
        return repo.findByUniverseIgnoreCase(universe);
    }

    @Override
    public List<ApiCharacter> searchByName(String nameSubstring) {
        return repo.findByNameContainingIgnoreCase(nameSubstring);
    }
}